-- =========================================================
-- Restore full bios for board members
-- Run this in Supabase SQL Editor
-- =========================================================

UPDATE board_members SET bio = '<p>Brad Mullins is Chief Operating Officer of Amware Companies. He provides over 22 years experience in executive management, specializing in sales and marketing, distribution, logistics, and business development. Brad is a results-oriented individual with innovative initiatives to drive growth, recognize efficiencies, implement and execute strategies associated with business plans and build strong customer relations.</p><p>His experience in business development has provided him a keen understanding of all facets of running a successful business. Brad brings a wide range of experience at an executive level with large companies like Frito-Lay, Nestle USA, and Michael Foods. His 12 years of experience with a private equity group has provided Brad with experience in purchasing companies and developing business plans to grow sales and reduce costs, making them attractive targets for an eventual acquisition.</p><p>Brad holds an undergraduate degree from Wittenberg University where he played four years of NCAA collegiate football, playing in the NCAA Division III National Championship in 1979. Brad was the defensive captain his senior year and earned multiple honors in the Ohio Athletic Conference. He was inducted into the Lorain Sports Hall of Fame in 2002.</p><p>Brad is also co-owner in a real estate management company with properties throughout the city of Lorain.</p><p>Brad commits a large portion of his free time using his business experience to sit on the Board of Directors for private companies as well as non profit organizations that include: Lorain County Board of Advisors for Junior Achievement, Board of Advisors for Teamsters Retirement Funds with 3 different locals, Board of Directors for Balanced Asset Management wealth management company, Board of Directors for Samuel Felton Foundation, and Board of Directors Vice Chair for Lorain Port Authority.</p>'
WHERE name = 'Brad Mullins';

UPDATE board_members SET bio = '<p>A native of Westlake who has lived in Lorain since 1985, Jeff Zellers is Vice President with The Brewer-Garrett Company. He has over 37 years of experience in engineering, energy services, construction support service maintenance and accounting to produce innovative and award-winning solutions.</p><p>Jeff is actively involved in developing the correct and cost-effective solutions for customers. He assembles the team of in-house professionals who are best suited for each specific project. He continues to be engaged with the project from development through final customer acceptance and implementation.</p><p>Jeff''s attention to detail, standards of quality and commitment to the client have made him a respected member of the HVAC industry. He has spoken on the benefits of Design/Build Contracting. He served as Treasurer for MCA, and has served on the Pipefitting Apprenticeship Committee and the Supplemental Unemployment Committee with Local 120 Pipefitters.</p><p>Jeff received his undergraduate degree in Industrial Technology from Ball State University. He and his wife Jane have three daughters and attend St. Anthony''s Parish. For the last three years, Jeff has played an integral role in the City of Lorain''s Zoning Board and Planning Commission.</p>'
WHERE name = 'Jeff Zellers';

UPDATE board_members SET bio = '<p>Jacqueline Jakacki was appointed to the port''s board of directors in May 2025. She was officially sworn in by Lorain Municipal Court Judge Mark Mihok before her first board meeting on June 10.</p><p>Jakacki is a realtor and team leader for the RE/MAX Above &amp; Beyond real estate company. In addition to the port board, Jakacki also serves as an executive board member for Main Street Lorain, as a committee member for the Cinco de Mayo Parade, and as co-chair of the Pets 4 Vets Golf Outing.</p><p>Jakacki''s four-year term began May 13, 2025, and continues through May 12, 2029.</p>'
WHERE name = 'Jacqueline Jakacki';

UPDATE board_members SET bio = '<p>Hannah Kiraly was appointed to the Lorain Port and Finance Authority Board of Directors in May 2022.</p><p>With nearly a decade dedicated to urban environments, Ms. Kiraly specializes in research, analysis, and data-driven solutions for complex community challenges. Her public service experience underscores the importance of informed policy development in addressing societal issues. She serves as Program Manager overseeing the Community and Economic Development Division at the City of Lorain''s Department of Building, Housing and Planning and holds positions as Board Member of the Lorain Port and Finance Authority, an Active Member of Main Street Lorain, and APA Ohio.</p><p>Ms. Kiraly earned her A.A. Degree from Cuyahoga Community College (2015), where she was named Ohio''s 2015 New Century Scholar for achieving the state''s top score among All-USA Community College Academic Team nominees. She pursued her passion further with a B.A. in Regional Planning and a Minor in Sustainable Urban Development from the Levin College of Urban Affairs at Cleveland State University (2017), followed by a Masters of Nonprofit Organizations from the Jack Joseph and Morton Mandel School of Applied Social Sciences at Case Western Reserve University (2021).</p><p>Throughout her academic and professional career, Ms. Kiraly has presented research at the American Association of Behavioral and Social Sciences Conference on urban environmental perspectives, served as a Panelist for Women in GIS for the Ohio Chapter of URISA, and been a guest speaker at her alma maters and local community organizations in Lorain, Ohio. In 2017, she was honored with the OCCDF Karen Kerns-Dresser Award for Public Service for her commitment and work towards increasing accessible food systems through urban agriculture in Northeast, Ohio.</p><p>Some of her career highlights include designing and implementing Master Plans, Strategic Plans, and Climate Action Plans for various jurisdictions, non-governmental agencies, nonprofits, and foundations in Northeast Ohio. She also pioneered the development and certification of the Lorain County Building Department through the Ohio Board of Building Standards and introduced the first bivariate mapping tool in Cuyahoga County to identify at-risk populations due to climate change implications.</p><p>Beyond her professional endeavors, she enjoys engaging in her photography and traveling with her husband.</p>'
WHERE name = 'Hannah Kiraly';

UPDATE board_members SET bio = '<p>Vassie Scott was appointed to the Lorain Port and Finance Authority Board of Directors in February 2021. He was born in Elyria, Ohio, raised in Lorain, Ohio, graduated from Clearview High School, and attended the University of Dayton.</p><p>He retired from Prudential Financial after 34 years of service, and is currently a member of The Scott Group, Inc., located at 520 Broadway Avenue in Lorain, Ohio. During his career he has received several awards with the Company and industry-wide, including several President Citations, the Prudential Leaders Council Award, and Lifetime status with the Million Dollar Round Table, which is achieved by consistently performing in the top ten percent of all financial advisors worldwide. During his career, he has earned the designations of Chartered Life Underwriter (CLU), Chartered Financial Consultant (ChFC), and Accredited Estate Planner (AEP).</p><p>Having been blessed with an exceptional professional career, his passions now include being of service to our local communities and sharing his experience, strengths and hope with the youth within our community. He was past president of the Lake Erie Landlord''s Association, past president of the Lorain County Board of Developmental Disabilities and was past treasurer for the Board of the Lorain County Community Action Agency. In the past, Vassie has mentored in Lorain City Schools in conjunction with the Lorain County Urban League, Elyria Salvation Army, and 100 Men of Lorain County.</p><p>He currently resides in Amherst, Ohio with his family. His personal interests include golf, chess, biking and traveling.</p>'
WHERE name = 'Vassie Scott';

UPDATE board_members SET bio = '<p>Michele Silva Arredondo was appointed to the Lorain Port and Finance Authority Board of Directors in November 2022. Her term will continue through January 8, 2025.</p>'
WHERE name = 'Michele Silva Arredondo';
